### ISSUE TITLE
Enhancement: link Substitute highlight group to IncSearch

### ISSUE THREAD

**Issue by Dmitrev** [zootedb0t/citruszest.nvim#21]
When you substitute text it's currently a bit subtle:

![image](https://github.com/zootedb0t/citruszest.nvim/assets/1260209/1056852d-08f6-4f6b-9e4f-37f0216403dd)

But when searching text it's pretty visbile:
![image](https://github.com/zootedb0t/citruszest.nvim/assets/1260209/088b01d3-d684-4d44-8f2b-c97a3139b6a4)

I think it would be great to have them look the same, not sure what you think.

I achieved this in my own config like so:

```lua
vim.api.nvim_set_hl(0, "Substitute", { link = "IncSearch" })
```

**Comment by zootedb0t** [comment]
Appreciate your observation. Feel free to submit a pull request for this, and I'll be happy to merge it.

**Comment by Dmitrev** [comment]
Thank you @zootedb0t for your quick reply on this. I made the PR to change this:
https://github.com/zootedb0t/citruszest.nvim
